builds:
    - binary: pocV
      main: ./cmd/pocV/
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - 386

archives:
    - id: tgz
      format: tar.gz
      replacements:
          darwin: macOS
      format_overrides:
          - goos: windows
            format: zip
